# CloneAI Wrapper Script
# Auto-generated by setup-clai.ps1
# This wrapper uses venv Python automatically when available

$CloneAIPath = "C:\Users\adars\OneDrive\Documents\CloneAI"
$VenvPath = Join-Path $CloneAIPath ".venv"
$VenvPython = Join-Path $VenvPath "Scripts\python.exe"

$originalLocation = Get-Location
try {
    Set-Location $CloneAIPath
    
    # Check if venv exists and use its Python directly
    if (Test-Path $VenvPython) {
        # Use venv Python (has all dependencies including document utilities)
        & "$VenvPython" -m agent.cli @args
    } else {
        # No venv, use system Python (email/calendar features only)
        python -m agent.cli @args
    }
}
finally {
    Set-Location $originalLocation
}
