# CloneAI PowerShell Setup Script
# This script sets up CloneAI to be usable from anywhere via 'clai' command

param(
    [switch]$Uninstall
)

$CloneAIPath = Split-Path -Parent $PSCommandPath
$WrapperScript = Join-Path $CloneAIPath "clai.ps1"

# Create the wrapper script that auto-uses venv Python
$WrapperContent = @"
# CloneAI Wrapper Script
# Auto-generated by setup-clai.ps1
# This wrapper uses venv Python automatically when available

`$CloneAIPath = "$CloneAIPath"
`$VenvPath = Join-Path `$CloneAIPath ".venv"
`$VenvPython = Join-Path `$VenvPath "Scripts\python.exe"

`$originalLocation = Get-Location
try {
    Set-Location `$CloneAIPath
    
    # Check if venv exists and use its Python directly
    if (Test-Path `$VenvPython) {
        # Use venv Python (has all dependencies including document utilities)
        & "`$VenvPython" -m agent.cli @args
    } else {
        # No venv, use system Python (email/calendar features only)
        python -m agent.cli @args
    }
}
finally {
    Set-Location `$originalLocation
}
"@

if ($Uninstall) {
    Write-Host "🗑️  Uninstalling CloneAI..." -ForegroundColor Yellow
    
    # Remove wrapper script
    if (Test-Path $WrapperScript) {
        Remove-Item $WrapperScript -Force
        Write-Host "   Removed wrapper script" -ForegroundColor Gray
    }
    
    # Remove from PATH
    $UserPath = [Environment]::GetEnvironmentVariable("Path", "User")
    if ($UserPath -like "*$CloneAIPath*") {
        $NewPath = ($UserPath -split ';' | Where-Object { $_ -ne $CloneAIPath }) -join ';'
        [Environment]::SetEnvironmentVariable("Path", $NewPath, "User")
        Write-Host "   Removed from PATH" -ForegroundColor Gray
    }
    
    Write-Host "✅ CloneAI uninstalled successfully!" -ForegroundColor Green
    Write-Host "   Please restart your terminal for changes to take effect." -ForegroundColor Cyan
    exit
}

Write-Host "🚀 Setting up CloneAI..." -ForegroundColor Cyan
Write-Host ""

# Step 1: Create wrapper script
Write-Host "1️⃣  Creating wrapper script..." -ForegroundColor Yellow
Set-Content -Path $WrapperScript -Value $WrapperContent -Force
Write-Host "   ✓ Created: $WrapperScript" -ForegroundColor Green

# Step 2: Add CloneAI directory to PATH
Write-Host ""
Write-Host "2️⃣  Adding to system PATH..." -ForegroundColor Yellow
$UserPath = [Environment]::GetEnvironmentVariable("Path", "User")

if ($UserPath -notlike "*$CloneAIPath*") {
    $NewPath = if ($UserPath) { "$UserPath;$CloneAIPath" } else { $CloneAIPath }
    [Environment]::SetEnvironmentVariable("Path", $NewPath, "User")
    Write-Host "   ✓ Added CloneAI to PATH" -ForegroundColor Green
} else {
    Write-Host "   ℹ️  Already in PATH" -ForegroundColor Gray
}

# Step 3: Check venv
Write-Host ""
Write-Host "3️⃣  Checking virtual environment..." -ForegroundColor Yellow
$VenvPath = Join-Path $CloneAIPath ".venv"
if (Test-Path $VenvPath) {
    Write-Host "   ✓ Virtual environment found" -ForegroundColor Green
    Write-Host "   ℹ️  Document utilities will auto-activate venv" -ForegroundColor Cyan
} else {
    Write-Host "   ⚠️  No virtual environment found" -ForegroundColor Yellow
    Write-Host "   ℹ️  Create one with: python -m venv .venv" -ForegroundColor Cyan
    Write-Host "   ℹ️  Then install deps: .\.venv\Scripts\Activate.ps1; pip install -r requirements.txt" -ForegroundColor Cyan
}

Write-Host ""
Write-Host "✅ CloneAI setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "📝 Next steps:" -ForegroundColor Cyan
Write-Host "   1. Restart your terminal (or run: `$env:Path = [System.Environment]::GetEnvironmentVariable('Path','User'))" -ForegroundColor White
Write-Host "   2. Test with: clai hi" -ForegroundColor White
Write-Host ""
Write-Host "💡 The 'clai' command is now available from any directory!" -ForegroundColor Green
Write-Host "   • Venv auto-activates when needed (for document utilities)" -ForegroundColor Gray
Write-Host "   • Email/calendar work without venv" -ForegroundColor Gray
Write-Host ""
Write-Host "🗑️  To uninstall: .\setup-clai.ps1 -Uninstall" -ForegroundColor Gray
